add:
  - [1,2,3,1]
  - [0.2,0.1,0.3,2]
  - ["12",1,1,3]
sub:
  - [1,5,-4,1]
  - [0.8,0.5,0.3,2]
  - [5.9," ",10.5,3]
mul:
  - [9,8,72,1]
  - [9.1,8.7,11.6,2]
  - [8," ",8,3]
div:
  - [10,2,5,1]
  - [2.5,5,0.5,2]
  - [5,0,8,3]
myids:
  - "int"
  - "float"
  - "error"